build:
  maxIssues: 0

style:
  active: true
  MagicNumber:
    active: false
  UnusedPrivateMember:
    active: true
    ignoreAnnotated: ['Composable']
  UnusedImports:
    active: false
  ReturnCount:
    active: false
  LoopWithTooManyJumpStatements:
    active: false
  ExplicitItLambdaParameter:
    active: false
  ForbiddenComment:
    active: false
  WildcardImport:
    active: false

complexity:
  active: true
  LongMethod:
    threshold: 200
  TooManyFunctions:
    thresholdInFiles: 50
    thresholdInClasses: 50
    thresholdInInterfaces: 30
    thresholdInEnums: 10
  CyclomaticComplexMethod:
    threshold: 40
  LongParameterList:
    functionThreshold: 12
    constructorThreshold: 12
  NestedBlockDepth:
    threshold: 6
  StringLiteralDuplication:
    active: false
  ComplexCondition:
    active: false

performance:
  active: true
  CouldBeSequence:
    active: false

potential-bugs:
  active: true
  UnreachableCode:
    active: true
  UnsafeCast:
    active: true
  ExplicitGarbageCollectionCall:
    active: true

exceptions:
  active: true
  SwallowedException:
    active: false
  PrintStackTrace:
    active: false
  InstanceOfCheckForException:
    active: false

naming:
  active: true
  FunctionNaming:
    active: true
    ignoreAnnotated: ['Composable', 'ComposableDestination', 'ComposableRoute', 'ComposableFunctionName']
  EnumNaming:
    active: false
  MatchingDeclarationName:
    active: false

coroutines:
  active: true
  GlobalCoroutineUsage:
    active: false
  InjectDispatcher:
    active: false
